spring:
  sleuth:
    reactor:
      enabled: true
  application:
    name: spring-gateway-demo
    http:
      encoding:
        charset: UTF-8
        enable: true
        force: true
      messages:
        encoding: UTF-8
  redis:
    host: oms.cache-redis-server
    port: 6379
#  http:
#    encoding:
#      charset: UTF-8
#      enable: true
#      force: true
#    messages:
#      encoding: UTF-8
  cloud:
    gateway:
        #default-filters:
        #  - AddResponseHeader=Authorization
        #  - PrefixPath=/oauth,/oms
        #discovery:
        #  locator:
        #    enabled: false
      routes:
      - id: routeoms
        uri: lb://CLOUD-TRACER-WITH-KAFKA
        predicates:
        - Path=/gw/**
        filters:
        - StripPrefix=1

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
    security:
      enabled: false
  health:
    rabbit:
      enabled: false

server:
  port: 7188
  #logging.level.com.dcits.trace=DEBUG

cloud:
  trace:
    url: http://10.7.19.120:9411/
    probability: 1.0
    enabled: true

eureka:
  client:
    register-with-eureka: true
    service-url: #指定注册中心的地址，以便使用服务发现功能
      defaultZone: http://localhost:1111/eureka
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    metadataMap:
      version: 1.0
#spring:

#spring:
#  cloud:
#    gateway:
#      default-filters:
#        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
#        - PrefixPath=/httpbin
#feign.hystrix.enabled=true
#spring.zipkin.base-url=http://127.0.0.1:9411
#spring.sleuth.sampler.probability=1.0
#management.endpoints.web.exposure.include=hystrix.stream