spring:
  application:
    name: lunar-gateway
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        default-filters:
        routes:
        #------------------------------------------------------------------------
        - id: route-to-lunar
          uri: http://localhost:5188
          predicates:
          - Path= /gw/**
          filters:
          - StripPrefix=1
        #------------------------------------------------------------------------

server:
  port: 6188
eureka:
  client:
    #register-with-eureka: true
    #fetch-registry: true
    defaultZone: http://localhost:1111/eureka/


#spring:


#feign.hystrix.enabled=true
#spring.zipkin.base-url=http://127.0.0.1:9411
#spring.sleuth.sampler.probability=1.0
#management.endpoints.web.exposure.include=hystrix.stream