package com.dcits.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.11
 * 2019-12-01T15:14:40.954+08:00
 * Generated source version: 3.2.11
 *
 */
@WebServiceClient(name = "SeasService",
                  wsdlLocation = "http://111.20.82.6:8060/seasws/services/SeasService?wsdl",
                  targetNamespace = "http://ws.seas")
public class SeasService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.seas", "SeasService");
    public final static QName SeasServiceHttpPort = new QName("http://ws.seas", "SeasServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://111.20.82.6:8060/seasws/services/SeasService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SeasService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://111.20.82.6:8060/seasws/services/SeasService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SeasService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SeasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeasService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SeasService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SeasService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SeasService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SeasServicePortType
     */
    @WebEndpoint(name = "SeasServiceHttpPort")
    public SeasServicePortType getSeasServiceHttpPort() {
        return super.getPort(SeasServiceHttpPort, SeasServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeasServicePortType
     */
    @WebEndpoint(name = "SeasServiceHttpPort")
    public SeasServicePortType getSeasServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(SeasServiceHttpPort, SeasServicePortType.class, features);
    }

}
