package com.dcits.jsbank.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.11
 * 2020-11-16T16:23:58.404+08:00
 * Generated source version: 3.2.11
 *
 */
@WebServiceClient(name = "WDGLYCDOrderQuerySOAPQSService",
                  wsdlLocation = "file:/Users/kongxiangwen/dev/spring-cloud-arch/spring-demos/docs/WDGLYCDOrderQueryProxyService.wsdl",
                  targetNamespace = "http://www.jscb.com.cn/wdgl/WDGLYCDOrderQuery/")
public class WDGLYCDOrderQuerySOAPQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.jscb.com.cn/wdgl/WDGLYCDOrderQuery/", "WDGLYCDOrderQuerySOAPQSService");
    public final static QName WDGLYCDOrderQuerySOAPQSPort = new QName("http://www.jscb.com.cn/wdgl/WDGLYCDOrderQuery/", "WDGLYCDOrderQuerySOAPQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/kongxiangwen/dev/spring-cloud-arch/spring-demos/docs/WDGLYCDOrderQueryProxyService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WDGLYCDOrderQuerySOAPQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/kongxiangwen/dev/spring-cloud-arch/spring-demos/docs/WDGLYCDOrderQueryProxyService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WDGLYCDOrderQuerySOAPQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WDGLYCDOrderQuerySOAPQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WDGLYCDOrderQuerySOAPQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WDGLYCDOrderQuerySOAPQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WDGLYCDOrderQuerySOAPQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WDGLYCDOrderQuerySOAPQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WDGLYCDOrderQueryService
     */
    @WebEndpoint(name = "WDGLYCDOrderQuerySOAPQSPort")
    public WDGLYCDOrderQueryService getWDGLYCDOrderQuerySOAPQSPort() {
        return super.getPort(WDGLYCDOrderQuerySOAPQSPort, WDGLYCDOrderQueryService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WDGLYCDOrderQueryService
     */
    @WebEndpoint(name = "WDGLYCDOrderQuerySOAPQSPort")
    public WDGLYCDOrderQueryService getWDGLYCDOrderQuerySOAPQSPort(WebServiceFeature... features) {
        return super.getPort(WDGLYCDOrderQuerySOAPQSPort, WDGLYCDOrderQueryService.class, features);
    }

}
